//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.DetalleFacturas = new HashSet<DetalleFacturas>();
        }
    
        public int idFactura { get; set; }
        public string tipoPago { get; set; }
        public decimal subTotal { get; set; }
        public decimal montoImpuesto { get; set; }
        public decimal descuento { get; set; }
        public decimal montoTotal { get; set; }
        public string idCliente { get; set; }
        public decimal transporte { get; set; }
        public Nullable<int> numeroCheque { get; set; }
        public string nombreBanco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturas> DetalleFacturas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
