//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.DetalleFacturas = new HashSet<DetalleFacturas>();
            this.Proveedores = new HashSet<Proveedores>();
        }
    
        public string codigoBarra { get; set; }
        public string descripcion { get; set; }
        public int precioCompra { get; set; }
        public int porcentajeIV { get; set; }
        public int porcentajeIVA { get; set; }
        public decimal precioVenta { get; set; }
        public string exento { get; set; }
        public string unidadMedida { get; set; }
        public string estado { get; set; }
        public int cantidad { get; set; }
        public int idCategoria { get; set; }
        public string foto { get; set; }
    
        public virtual CategoriaProductos CategoriaProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturas> DetalleFacturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proveedores> Proveedores { get; set; }
    }
}
